# see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

jms:
  username: jms username
  password: jms password
  url: jms url

---
spring:
  profiles: de

jms:
  username: jms username german


---
spring:
  profiles: fr

jms:
  username: jms username français
